guns:
  Glock17:
    display_name: Glock 17
    max_ammo: 32
    reload_time: 1200
    # auto / burst
    #fire_rate: auto #to morš narest to nevem kaj nej bi ble opcije
    bullet_per_shot: 1
    damage: 10
    accuracy: 0.9
    range: 100
    material:
    recoil: 1.0
    ammo_type: Pistol_Ammo
    shooting_sound: #tle dodaj nek sound
    reloading_sound: BAT_DEATH
    empty_sound: #tle dodaj nek sound
  '2':
    display_name: gun
    max_ammo: 4
