guns:
  '1': #id
    display_name: Glock 17
    max_ammo: 32
    reload_time: 1200
    bullet_per_shot: 1
    damage: 3
    accuracy: 0.9
    range: 100
    material: COCOA_BEANS
    recoil: 1.0
    ammo_type: Pistol_Ammo
    shooting_sound: ENTITY_BAT_HURT
    reloading_sound: UI_BUTTON_CLICK
    empty_sound: ENTITY_BAT_DEATH

  '2': #id
    display_name: "Desert Eagle"
    max_ammo: 7
    reload_time: 1200
    bullet_per_shot: 1
    damage: 10
    accuracy: 1
    range: 150
    material: WHITE_DYE
    recoil: 2.0
    ammo_type: Pistol_Ammo
    shooting_sound: ENTITY_BAT_HURT
    reloading_sound: UI_BUTTON_CLICK
    empty_sound: ENTITY_BAT_DEATH

  '3': #id
    display_name: M9
    max_ammo: 12
    reload_time: 1200
    bullet_per_shot: 1
    damage: 3
    accuracy: 1
    range: 75
    material: ORANGE_DYE
    recoil: 0.2
    ammo_type: Pistol_Ammo
    shooting_sound: ENTITY_BAT_HURT
    reloading_sound: UI_BUTTON_CLICK
    empty_sound: ENTITY_BAT_DEATH
  '4': #id
    display_name: "Colt ACP"
    max_ammo: 7
    reload_time: 1200
    bullet_per_shot: 1
    damage: 3.5
    accuracy: 1
    range: 80
    material: MAGENTA_DYE
    recoil: 0.3
    ammo_type: Pistol_Ammo
    shooting_sound: ENTITY_BAT_HURT
    reloading_sound: UI_BUTTON_CLICK
    empty_sound: ENTITY_BAT_DEATH
  '5': #id
    display_name: "Glock 17"
    max_ammo: 17
    reload_time: 1200
    bullet_per_shot: 1
    damage: 5
    accuracy: 1
    range: 80
    material: LIGHT_BLUE_DYE
    recoil: 0.2
    ammo_type: Pistol_Ammo
    shooting_sound: ENTITY_BAT_HURT
    reloading_sound: UI_BUTTON_CLICK
    empty_sound: ENTITY_BAT_DEATH
  '6': #id
    display_name: "Smith & Wesson 686"
    max_ammo: 6
    reload_time: 2200
    bullet_per_shot: 1
    damage: 6
    accuracy: 0.85
    range: 65
    material: YELLOW_DYE
    recoil: 0.7
    ammo_type: Pistol_Ammo
    shooting_sound: ENTITY_BAT_HURT
    reloading_sound: UI_BUTTON_CLICK
    empty_sound: ENTITY_BAT_DEATH
  '7': #id
    display_name: "Colt Python"
    max_ammo: 6
    reload_time: 1200
    bullet_per_shot: 1
    damage: 7
    accuracy: 1
    range: 90
    material: LIME_DYE
    recoil: 1.2
    ammo_type: Pistol_Ammo
    shooting_sound: ENTITY_BAT_HURT
    reloading_sound: UI_BUTTON_CLICK
    empty_sound: ENTITY_BAT_DEATH
  '8': #id
    display_name: MP5
    max_ammo: 30
    reload_time: 1200
    bullet_per_shot: 1
    damage: 3.5
    accuracy: 1
    range: 75
    material: PINK_DYE
    recoil: 0.83
    ammo_type: SMG_Ammo
    shooting_sound: ENTITY_BAT_HURT
    reloading_sound: UI_BUTTON_CLICK
    empty_sound: ENTITY_BAT_DEATH
  '9': #id
    display_name: UMP45
    max_ammo: 30
    reload_time: 1200
    bullet_per_shot: 1
    damage: 3.4
    accuracy: 1
    range: 78
    material: GRAY_DYE
    recoil: 1.0
    ammo_type: SMG_Ammo
    shooting_sound: ENTITY_BAT_HURT
    reloading_sound: UI_BUTTON_CLICK
    empty_sound: ENTITY_BAT_DEATH
  '10': #id
    display_name: Uzi
    max_ammo: 30
    reload_time: 1200
    bullet_per_shot: 1
    damage: 3.5
    accuracy: 0.7
    range: 100
    material: LIGHT_GRAY_DYE
    recoil: 0.6
    ammo_type: SMG_Ammo
    shooting_sound: ENTITY_BAT_HURT
    reloading_sound: UI_BUTTON_CLICK
    empty_sound: ENTITY_BAT_DEATH
  '11': #id
    display_name: "M4 Carbine"
    max_ammo: 30
    reload_time: 3000
    bullet_per_shot: 1
    damage: 5
    accuracy: 0.95
    range: 140
    material: CYAN_DYE
    recoil: 0.5
    ammo_type: Rifle_Ammo
    shooting_sound: ENTITY_BAT_HURT
    reloading_sound: UI_BUTTON_CLICK
    empty_sound: ENTITY_BAT_DEATH
  '12': #id
    display_name: M16A4
    max_ammo: 30
    reload_time: 3000
    bullet_per_shot: 1
    damage: 5.5
    accuracy: 0.85
    range: 140
    material: PURPLE_DYE
    recoil: 1.0
    ammo_type: Rifle_Ammo
    shooting_sound: ENTITY_BAT_HURT
    reloading_sound: UI_BUTTON_CLICK
    empty_sound: ENTITY_BAT_DEATH
  '13': #id
    display_name: "Steyr AUG"
    max_ammo: 40
    reload_time: 3000
    bullet_per_shot: 1
    damage: 4
    accuracy: 1
    range: 150
    material: BLUE_DYE
    recoil: 0.5
    ammo_type: Rifle_Ammo
    shooting_sound: ENTITY_BAT_HURT
    reloading_sound: UI_BUTTON_CLICK
    empty_sound: ENTITY_BAT_DEATH
  '14': #id
    display_name: SCAR-L
    max_ammo: 40
    reload_time: 3000
    bullet_per_shot: 1
    damage: 5
    accuracy: 0.9
    range: 150
    material: BROWN_DYE
    recoil: 0.5
    ammo_type: Rifle_Ammo
    shooting_sound: ENTITY_BAT_HURT
    reloading_sound: UI_BUTTON_CLICK
    empty_sound: ENTITY_BAT_DEATH
  '15': #id
    display_name: AK-47
    max_ammo: 40
    reload_time: 3000
    bullet_per_shot: 1
    damage: 5.5
    accuracy: 0.6
    range: 170
    material: GREEN_DYE
    recoil: 1.0
    ammo_type: Rifle_Ammo
    shooting_sound: ENTITY_BAT_HURT
    reloading_sound: UI_BUTTON_CLICK
    empty_sound: ENTITY_BAT_DEATH
  '16': #id
    display_name: AKMS
    max_ammo: 30
    reload_time: 3000
    bullet_per_shot: 1
    damage: 3.5
    accuracy: 0.6
    range: 120
    material: RED_DYE
    recoil: 1.2
    ammo_type: Rifle_Ammo
    shooting_sound: ENTITY_BAT_HURT
    reloading_sound: UI_BUTTON_CLICK
    empty_sound: ENTITY_BAT_DEATH
  '17': #id
    display_name: Heckler & Koch HK416
    max_ammo: 25
    reload_time: 3000
    bullet_per_shot: 1
    damage: 4
    accuracy: 0.9
    range: 130
    material: BLACK_DYE
    recoil: 0.5
    ammo_type: Rifle_Ammo
    shooting_sound: ENTITY_BAT_HURT
    reloading_sound: UI_BUTTON_CLICK
    empty_sound: ENTITY_BAT_DEATH
  '18': #id
    display_name: G36C
    max_ammo: 30
    reload_time: 3000
    bullet_per_shot: 1
    damage: 3.9
    accuracy: 0.5
    range: 140
    material: SUGAR
    recoil: 1.0
    ammo_type: Rifle_Ammo
    shooting_sound: ENTITY_BAT_HURT
    reloading_sound: UI_BUTTON_CLICK
    empty_sound: ENTITY_BAT_DEATH
