guns:
  '1': #id
    display_name: Glock 17
    max_ammo: 32
    reload_time: 1200
    bullet_per_shot: 1
    damage: 3
    accuracy: 0.9
    range: 100
    material:
    recoil: 1.0
    ammo_type: Pistol_Ammo
    shooting_sound: BAT_HURT
    reloading_sound: BAT_TAKEOFF
    empty_sound: BAT_DEATH
  '2':
  display_name: Desert Eagle
  max_ammo: 7
  reload_time: 1200
  bullet_per_shot: 1
  damage: 10
  accuracy: 1
  range: 150
  material:
  recoil: 2.0
  ammo_type: Pistol_Ammo
  shooting_sound: #need to be added
  reloading_sound: #need to be added
  empty_sound: BAT_DEATH
